import Navbar from "../components/Navbar"

export const metadata = {
  title: 'Mi pagina',
  description: 'Generated by Next.js',
  keywords: 'nextjs, react, seo',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <Navbar/>
      {children}</body>
    </html>
  )
}
